### ISSUE TITLE
Please lets have the data resource in `main.tf`

### ISSUE THREAD

**Issue by fatz** [dcos-terraform/terraform-aws-vpc-peering#1]
https://github.com/dcos-terraform/terraform-aws-vpc-peering/blob/af2e48cb01ec73356c390f0e1326af608bdb7c2c/data.tf#L1-L15

Its just 15 lines. IMO Its better to read and understand if the main code is living in a single file

**Comment by bernadinm** [comment]
thanks @fatz, I created PR https://github.com/dcos-terraform/terraform-aws-vpc-peering/pull/4 to address this issue. We can merge this and mark this case as closed
