### ISSUE TITLE
This should not be a static text.

### ISSUE THREAD

**Issue by fatz** [dcos-terraform/terraform-aws-vpc-peering#2]
https://github.com/dcos-terraform/terraform-aws-vpc-peering/blob/af2e48cb01ec73356c390f0e1326af608bdb7c2c/main.tf#L96

I think this should contain at least the peered VPC ids

https://github.com/dcos-terraform/terraform-aws-vpc-peering/blob/af2e48cb01ec73356c390f0e1326af608bdb7c2c/main.tf#L105

**Comment by bernadinm** [comment]
If we do this, the VPC peer would have a cirular dependancy on each other:

```
resource "aws_vpc_peering_connection" "peering" {
  provider    = "aws.this"
  vpc_id      = "${var.this_vpc_id}"
  peer_vpc_id = "${var.peer_vpc_id}"
  peer_region = "${data.aws_region.peer.name}"

  tags = "${merge(var.tags, map("Name", "VPC Peering between default and bursting"))}"
}

# Accepter's side of the connection.
resource "aws_vpc_peering_connection_accepter" "peer" {
  provider                  = "aws.peer"
  vpc_peering_connection_id = "${aws_vpc_peering_connection.peering.id}"
  auto_accept               = true

  tags = "${merge(var.tags, map("Name", "Accepter"))}"
}
```

aws_vpc_peering_connection.peering.tags <=> aws_vpc_peering_connection.peer.tags

This would work if we could change a tag on a resource dynamically but this is currently a limitation at this time of writing.

`https://github.com/terraform-providers/terraform-provider-aws/issues/3143`

**Comment by fatz** [comment]
No need for dependencies. Just use the variables

**Comment by bernadinm** [comment]
oh, I'm sorry. I read this wrong, I thought you mean't the pcx of the remote site. I'll get a PR to complete this change. Thanks @fatz !
